name: edgex-device-modbus
base: core20
license: Apache-2.0
adopt-info: metadata

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: <= hanoi
# 2: >= ireland 
epoch: 2

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/device-modbus]

apps:
  device-modbus:
    adapter: full
    command: bin/device-modbus -confdir $SNAP_DATA/config/device-modbus -profile res --registry $CONSUL_ADDR
    command-chain:
      - bin/startup-env-var.sh
    environment:
      CONSUL_ADDR: "consul://localhost:8500"
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-modbus/res/profiles"
      DEVICE_DEVICESDIR: "$SNAP_DATA/config/device-modbus/res/devices"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-modbus/secrets-token.json
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

plugs:
  device-config:
    interface: content
    target: $SNAP_DATA/config/device-modbus

parts:
  hooks:
    source: snap/local/hooks
    plugin: make
    build-snaps:
      - go/1.17/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./cmd/configure/configure "$SNAPCRAFT_PART_INSTALL/snap/hooks/configure"
      install -DT ./cmd/install/install "$SNAPCRAFT_PART_INSTALL/snap/hooks/install"

  device-modbus:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [git, libzmq3-dev, zip, pkg-config]
    build-snaps:
      - go/1.17/stable
    stage-packages: [libzmq5]
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      go mod tidy -compat=1.17
      make build

      install -DT "./cmd/device-modbus" "$SNAPCRAFT_PART_INSTALL/bin/device-modbus"

      install -d "$SNAPCRAFT_PART_INSTALL/config/device-modbus/res/"

      install -DT "./cmd/res/configuration.toml" "$SNAPCRAFT_PART_INSTALL/config/device-modbus/res/configuration.toml"

      for fpath in ./cmd/res/profiles/*; do
          fname=$(basename "$fpath")
          install -DT "./cmd/res/profiles/${fname}" \
          "$SNAPCRAFT_PART_INSTALL/config/device-modbus/res/profiles/${fname}"
      done

      for fpath in ./cmd/res/devices/*.toml; do
          fname=$(basename "$fpath")
          install -DT "./cmd/res/devices/${fname}" \
          "$SNAPCRAFT_PART_INSTALL/config/device-modbus/res/devices/${fname}"
      done

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-modbus/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-modbus/LICENSE"
  config-common:
    plugin: dump
    source: snap/local/runtime-helpers

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png
      
      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR
      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION
      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-device-modbus.metainfo.xml]  