name: edgex-device-modbus
base: core22
license: Apache-2.0
summary: EdgeX Modbus Device Service
description: Refer to https://snapcraft.io/edgex-device-modbus
adopt-info: device-modbus

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh, geneva, hanoi
# 2: ireland, jakarta, kamakura, levski
# 3: minnesota
epoch: 3

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: [$SNAP_DATA/device-modbus]
plugs:
  device-modbus-config:
    interface: content
    target: $SNAP_DATA/config/device-modbus

apps:
  device-modbus:
    command: bin/device-modbus --configDir $SNAP_DATA/config/device-modbus/res --configProvider --registry
    command-chain:
      - bin/source-env-file.sh
    environment:
      DEVICE_PROFILESDIR: "$SNAP_DATA/config/device-modbus/res/profiles"
      DEVICE_DEVICESDIR: "$SNAP_DATA/config/device-modbus/res/devices"
      SECRETSTORE_TOKENFILE: $SNAP_DATA/device-modbus/secrets-token.json
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

parts:
  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $CRAFT_PART_SRC
      make build
      install -DT ./helper-go $CRAFT_PART_INSTALL/bin/helper-go

  device-modbus:
    source: .
    plugin: make
    build-packages: 
      - git
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $CRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # set the version of the snap
      craftctl set version=$VERSION
      
      # write version to file for the build
      echo $VERSION > VERSION

      make build

      install -DT "./cmd/device-modbus" "$CRAFT_PART_INSTALL/bin/device-modbus"

      RES=$CRAFT_PART_INSTALL/config/device-modbus/res/
      mkdir -p $RES
      cp -r cmd/res/* $RES
      
      DOC=$CRAFT_PART_INSTALL/usr/share/doc/device-modbus
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh

