name: edgex-device-modbus
base: core18
version: "replace-me"
license: Apache-2.0
version-script: |
  echo $(cat VERSION)-$(date +%Y%m%d)+$(git rev-parse --short HEAD)
summary: Connect data Modbus to EdgeX using device-modbus reference Device Service
title: EdgeX MQTT Device Service
description: |
  The official reference EdgeX device-modbus Device Service built using the 
  device-sdk-go to interact with Modbus devices. 
  Initially the daemon in the snap is disabled - a device profile must be
  provisioned externally with core-metadata or provided to device-modbus inside
  "$SNAP_DATA/config/device-modbus/res" before starting.

# TODO: add armhf when the project supports this
architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# edinburgh release is epoch 1
epoch: 1

apps:
  device-modbus:
    adapter: none
    command: bin/device-modbus $CONF_ARG $PROFILE_ARG $REGISTRY_ARG
    environment:
      CONF_ARG: "--confdir=$SNAP_DATA/config/device-modbus"
      PROFILE_ARG: "--profile=res"
      REGISTRY_ARG: "--registry=consul://localhost:8500"
    daemon: simple
    plugs: [network, network-bind]

parts:
  go:
    plugin: nil
    build-packages: [curl]
    source: snap/local
    override-build: |
      # use dpkg architecture to figure out our target arch
      # note - we specifically don't use arch
      case "$(dpkg --print-architecture)" in
        amd64)
          FILE_NAME=go1.11.9.linux-amd64.tar.gz
          FILE_HASH=e88aa3e39104e3ba6a95a4e05629348b4a1ec82791fb3c941a493ca349730608
          ;;
        arm64)
          FILE_NAME=go1.11.9.linux-arm64.tar.gz
          FILE_HASH=892ab6c2510c4caa5905b3b1b6a1d4c6f04e384841fec50881ca2be7e8accf05
          ;;
        armhf)
          FILE_NAME=go1.11.9.linux-armv6l.tar.gz
          FILE_HASH=f0d7b039cae61efdc346669f3459460e3dc03b6c6de528ca107fc53970cba0d1
          ;;
        i386)
          FILE_NAME=go1.11.9.linux-386.tar.gz
          FILE_HASH=0fa4001fcf1ef0644e261bf6dde02fc9f10ae4df6d74fda61fc4d3c3cbef1d79
          ;;
      esac
      # download the archive, failing on ssl cert problems
      curl https://dl.google.com/go/$FILE_NAME -O
      echo "$FILE_HASH $FILE_NAME" > sha256
      sha256sum -c sha256 | grep OK
      tar -C $SNAPCRAFT_STAGE -xf go*.tar.gz --strip-components=1
    prime:
      - "-*"

  device-modbus:
    source: .
    plugin: make
    build-packages: [git]
    after: [go]
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build

      install -DT "./cmd/device-modbus" "$SNAPCRAFT_PART_INSTALL/bin/device-modbus"

      # FIXME: settings can't be overridden from the cmd-line!
      # Override 'LogFile' and 'LoggingRemoteURL'
      install -d "$SNAPCRAFT_PART_INSTALL/config/device-modbus/res/"

      cat "./cmd/res/configuration.toml" | \
        sed -e s:\"./device-modbus.log\":\'\$SNAP_COMMON/device-modbus.log\': \
          -e s:'ProfilesDir = \"./res\"':'ProfilesDir = \"\$SNAP_DATA/config/device-modbus/res\"': > \
        "$SNAPCRAFT_PART_INSTALL/config/device-modbus/res/configuration.toml"

      install -DT "./cmd/Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-modbus/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/device-modbus/LICENSE"
